name: NIF
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.11
  - pytorch=2.1.1
  - pytorch-cuda=12.1
  - torchvision
  - matplotlib
  - pip
  - pip:
    - plyfile
    - polyscope