name: NIF
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.11
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - torchvision
  - matplotlib
  - pip
  - pip:
    - plyfile
    - polyscope
